#!/bin/bash

cd creation_class/scripts
python3 main.py
read -n1 -r -p 'Press any key to continue.'
cd ../../creation_class_advanced/scripts
python3 main.py
read -n1 -r -p 'Press any key to continue.'
cd ../../creation_class_physics/scripts
python3 main.py
read -n1 -r -p 'Press any key to continue.'
cd ../../genesis_class/scripts
python3 main.py
read -n1 -r -p 'Press any key to continue.'
cd ../../genesis_class_advanced/scripts
python3 main.py
read -n1 -r -p 'Press any key to continue.'
cd ../../genesis_class_spin/scripts
python3 main.py
read -n1 -r -p 'Press any key to continue.'
cd ../../adam_class/scripts
python3 main.py
read -n1 -r -p 'Press any key to continue.'
cd ../../adam_class_physics/scripts
python3 main.py
read -n1 -r -p 'Press any key to continue.'
cd ../../eve_class/scripts
python3 main.py
read -n1 -r -p 'Press any key to continue.'
cd ../../eve_class_advanced/scripts
python3 main.py
read -n1 -r -p 'Press any key to continue.'
cd ../../eve_class_gms/scripts
python3 main.py
read -n1 -r -p 'Press any key to continue.'
cd ../../eve_class_particles/scripts
python3 main.py
read -n1 -r -p 'Press any key to continue.'
cd ../../checkerboard_class/scripts
python3 main.py
read -n1 -r -p 'Press any key to continue.'
cd ../../checkerboard_class_advanced/scripts
python3 main.py
read -n1 -r -p 'Press any key to continue.'
cd ../../checkerboard_class_agent/scripts
python3 main.py
read -n1 -r -p 'Press any key to continue.'
cd ../../checkersmarkii_class/scripts
python3 main.py
read -n1 -r -p 'Press any key to continue.'
